add cards
js-tasks-ru/htmlcss-20220120_marina31 pull request #7
Opened 2022-02-15 13:08 UTC by moiseyka86

2022-02-15 13:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-16 21:11 UTC, GSemikozov requested changes

2022-02-16 21:11 UTC, GSemikozov commented on components/cards/card.css
> +
если карточку сделать флексом, то здесь будет хорошая. возможность растянуть .card__top и сместить тайтл вниз через flex-grow: 1 (он будет всегда внизу, что будет соответствовать макету)

2022-02-17 09:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-18 09:02 UTC, GSemikozov approved these changes

2022-02-18 09:02 UTC, merged